version: "3.7"

services:
  mssql:
    container_name: mssql_standard_2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    user: root
    depends_on:
      - nexus
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: jEn125us!
      MSSQL_PID: Standard
      SA_PASSWORD: jEn125us!
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "jEn125us!", "-Q", "select 1" ]
      interval: 10s
      retries: 10
    volumes:
      - /home/agrimgrover/docker/mssql:/var/opt/mssql

#db encryption key=PoBj9MZunVVVH3V6sZdc264hdJ3M83

  nexus:
    container_name: nexus2
    image: sonatype/nexus
    ports:
      - 8200:8081

  teamcity-server:
    container_name: teamcity-server-instance
    image: jetbrains/teamcity-server
    ports:
      - 8100:8111
    depends_on:
      - mssql
    volumes:
      - /home/agrimgrover/docker/teamcity/data:/data/teamcity_server/datadir
      - /home/agrimgrover/docker/teamcity/logs:/opt/teamcity/logs

  teamcity-agent-0:
    container_name: teamcity-agent-instance-0
    image: jetbrains/teamcity-agent
    depends_on:
      - teamcity-server
    volumes:
      - /home/agrimgrover/docker/teamcity/agent0:/data/teamcity_agent/conf
    environment:
      SERVER_URL: docker.gcs.net.in:8100

  teamcity-agent-1:
    container_name: teamcity-agent-instance-1
    image: jetbrains/teamcity-agent
    depends_on: [teamcity-agent-0]
    volumes:
      - /home/agrimgrover/docker/teamcity/agent1:/data/teamcity_agent/conf
    environment:
      SERVER_URL: docker.gcs.net.in:8100

  teamcity-agent-2:
    container_name: teamcity-agent-instance-2
    image: jetbrains/teamcity-agent
    depends_on: [teamcity-agent-1]
    volumes:
      - /home/agrimgrover/docker/teamcity/agent2:/data/teamcity_agent/conf
    environment:
      SERVER_URL: docker.gcs.net.in:8100

  octopus-server:
    container_name: octopus_server
    image: octopusdeploy/octopusdeploy:latest
    privileged: "true"
    depends_on: [teamcity-agent-2]
    environment:
      ACCEPT_EULA: "Y"
      OCTOPUS_SERVER_NODE_NAME: "octopus_server_local"
      DB_CONNECTION_STRING: "Server=docker.gcs.net.in,1433;Database=OctopusDeploy;User=sa;Password=jEn125us!"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "Passw0rd123"
      ADMIN_EMAIL: "agrimgrover@hotmail.com"
      OCTOPUS_SERVER_BASE64_LICENSE:
      MASTER_KEY: "X65rHSPYEc4N7mtn/XIrmA=="
    ports:
      - 8000:8080
      - 10943:10943
    volumes:
      - /home/agrimgrover/docker/octopus/repository:/repository
      - /home/agrimgrover/docker/octopus/artifacts:/artifacts
      - /home/agrimgrover/docker/octopus/taskLogs:/taskLogs
      - /home/agrimgrover/docker/octopus/cache:/cache
      - /home/agrimgrover/docker/octopus/import:/import

# Create a new master key with the command: openssl rand 16 | base64
#Base64 version of Masterkey = X65rHSPYEc4N7mtn/XIrmA==



#teamcity_agent: /home/agrimgrover/docker/teamcity/agents
